# Generated by Django 4.2.2 on 2023-07-20 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epredmet', '0002_unansweredquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unansweredquestion',
            name='intent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='epredmet.intent'),
        ),
    ]
